config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show,:new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update] 
  
  resources :orders, only: [:new, :create, :show, :index] do
    get 'search', on: :collection 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user

  validates :code, :estimated_delivery_date, presence: true 
  validate :estimated_delivery_date_is_future

  before_validation :generate_code

  private 

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end 

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, "deve ser futura.")
    end 
  end 
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  validates :name, :weight, :width, :height, :depth, :sku, :supplier, presence: true
  validates :sku, uniqueness: true 
  validates :width, :height, :depth, :weight, numericality: {greater_than: 0}
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many  :product_models 
    validates :brand_name, :corporate_name, :registration_number, :email,  presence: true
    validates :registration_number, length:  {is: 14 } 
    validates :registration_number, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders  

  def description
    "#{name} - #{email}"
  end 
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
    validates :name, :code, :city, :description, :address, :cep, :area, presence: true
    validates :cep, length:  {is: 9 } 
    validates :code, :name, uniqueness: true 

    def full_description
        "#{code} - #{name}"
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @warehouses = Warehouse.all 
    end 
end 

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def index
        @orders = current_user.orders 
    end 
    
    def new
        @order = Order.new 
        @warehouses = Warehouse.all
        @suppliers = Supplier.all
    end

    def create
        order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
        @order = Order.new(order_params)
        @order.user = current_user
        @order.save!
        redirect_to @order, notice: 'Pedido registrado com sucesso'
    end
    
    def show
        @order = Order.find(params[:id])
    end 

    def search
        @code = params["query"]
        @orders = Order.where("code LIKE ?", "%#{@code}%")
    end 
end 

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
    before_action :set_product_model, only: [:show, :edit, :update]
    before_action :set_supplier, only: [:new, :edit]
    
    
    def index
        @product_models = ProductModel.all 
    end 

    def show
    end 

    def new
        @product_model = ProductModel.new
    end

    def create
        @product_model = ProductModel.new(product_model_params)
        if @product_model.save()
            redirect_to @product_model, notice: 'Modelo de Produto cadastrado com sucesso.'
        else 
            @suppliers = Supplier.all
            flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto.'
            render 'new' 
        end 
    end 

    def edit
    end 

    def update
        if @product_model.update(product_model_params)
            redirect_to @product_model, notice: 'Modelo de Produto atualizado com sucesso.'
        else 
            @suppliers = Supplier.all
            flash.now[:notice] = 'Não foi possível atualizar o modelo de produto.'
            render 'edit' 
        end 
    end 

    private

    def set_product_model 
        @product_model = ProductModel.find(params[:id])
    end 

    def product_model_params
        params.require(:product_model).permit(:name, :height, :width, :depth, :weight, :sku, :supplier_id)
    end 
    
    def set_supplier
        @suppliers = Supplier.all
    end 
end 

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
    before_action :set_supplier, only: [:show, :edit, :update]
    
    
    def index
        @suppliers = Supplier.all 
    end 

    def show
        @product_model = @supplier.product_models
    end 

    def new
        @supplier = Supplier.new 
    end 

    def create
        @supplier = Supplier.new(supplier_params)
        if @supplier.save()
            redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso.'
        else
            flash.now[:notice] = 'Fornecedor não cadastrado.'
            render 'new'
        end 
    end 

    def edit
    end 

    def update
        if @supplier.update(supplier_params)
            redirect_to @supplier, notice: 'Fornecedor atualizado com sucesso.'
        else
            flash.now[:notice] = 'Não foi possível atualizar o fornecedor.'
            render 'edit'
        end 
    end 

    private

    def set_supplier
        @supplier = Supplier.find(params[:id])
    end 

    def supplier_params 
        params.require(:supplier).permit(:brand_name, :corporate_name, :registration_number, 
                                         :full_address, :city, :state, :email, :telephone)
    end
end 

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController 
    before_action :set_warehouse, only: [:show, :edit, :update, :destroy]
    
    
    def show; end 

    def new
        @warehouse = Warehouse.new 
    end 

    def create
        @warehouse = Warehouse.new(warehouse_params)
        if @warehouse.save()
            redirect_to root_path, notice: 'Galpão cadastrado com sucesso.'
        else
            flash.now[:notice] = 'Galpão não cadastrado.'
            render 'new'
        end 
    end 

    def edit     
    end 

    def update
        if @warehouse.update(warehouse_params)
            redirect_to warehouse_path(@warehouse.id), notice: 'Galpão atualizado com sucesso.'
        else
            flash.now[:notice] = 'Não foi possível atualizar o galpão.'
            render 'edit'
        end 
    end 

    def destroy
        @warehouse.destroy
        redirect_to root_path, notice: 'Galpão removido com sucesso.'
    end 

    private 

    def set_warehouse
        @warehouse = Warehouse.find(params[:id])
    end 

    def warehouse_params
        params.require(:warehouse).permit(:name, :code, :city, :description, :address, 
                                            :cep, :area)
    end 
    
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Galpões</h1>   
    <div>
        <%=link_to('Cadastrar Galpão', new_warehouse_path)%>
    </div>
    <% @warehouses.each do |w| %>
        <div>
            <h2><%= link_to(w.name, w)%></h2>
            <dl>
                <dt>Código:</dt>
                <dd><%= w.code %></dd>

                <dt>Cidade:</dt>
                <dd><%= w.city %></dd>

                <dt>Área:</dt>
                <dd><%= w.area %> m2</dd>
            </dl>
        </div>
    <% end %>

    <% if @warehouses.empty? %>
        <p>Não existem galpões cadastrados</p>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
    <%= link_to root_path do %>
      <h1>Galpões & Estoque</h1>
    <% end %>
      <nav>
        <%= link_to('Galpões', root_path)%> | 
        <%= link_to('Fornecedores', suppliers_path)%> | 
        <%= link_to('Modelos de Produtos', product_models_path)%> | 
        <%= link_to('Registrar Pedido', new_order_path)%> | 
        <%= link_to('Meus Pedidos', search_orders_path)%>

        <% if user_signed_in?%>
          <%=form_with(url: search_orders_path, method: :get) do |f|%>
            <%= f.label :query, 'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar'%>
          <% end %>
          <%= current_user.description%> 
          <%= button_to('Sair', destroy_user_session_path, method: :delete)%>
          <% else %>
          <%= link_to('Entrar', new_user_session_path)%>
        <% end%>
      </nav>
    </header>
    <main>
      <div>
        <%=flash[:notice]%>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_order.html.erb
<dl>
        <dt><%= Order.human_attribute_name(:code) %>:</dt>
        <dd><%= order.code %></dd>

        <dt><%= Order.human_attribute_name(:warehouse_id) %>:</dt>
        <dd><%= order.warehouse.full_description %></dd>

        <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
        <dd><%= order.supplier.corporate_name %></dd>
    </dl>

app/views/orders/index.html.erb
<h1>Meus Pedidos</h1>

<% orders.each do |order| %>
    <%= render order  %>
<%end%>

app/views/orders/new.html.erb
<h1>Registrar Pedido</h1>

<%= form_with(model: @order) do |f| %>
    <div>
        <%= f.label :warehouse_id %>
        <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
    </div>
       <div>
        <%= f.label :supplier_id %>
        <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
    </div>
    <div>
        <%= f.label :estimated_delivery_date %>
        <%= f.date_field :estimated_delivery_date %>
    </div>

    <%= f.submit 'Gravar' %>

<% end %>

app/views/orders/search.html.erb
<h1> Resultados da Busca por: <%= @code %></h1>

<p><%= @orders.count %> <%= Order.model_name.human(count: @orders.count).downcase %> <%= t(:found, count: @orders.count)%></p>
<% @orders.each do |order|%>
    <%= render order%>
<%end%>

app/views/orders/show.html.erb
<h1><%= Order.model_name.human %> <%= @order.code %></h1>
<dl>
    <dt><%= Order.human_attribute_name(:warehouse_id) %>:</dt>
    <dd><%= @order.warehouse.full_description %></dd>

    <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
    <dd><%= @order.supplier.corporate_name %></dd>

    <dt><%= Order.human_attribute_name(:user) %>:</dt>
    <dd><%= @order.user.description %></dd>

    <dt><%= Order.human_attribute_name(:estimated_delivery_date) %>:</dt>
    <dd><%= I18n.localize(@order.estimated_delivery_date) %></dd>
</dl>

app/views/product_models/_form.html.erb
<%=form_with(model: @product_model) do |pm| %>
    <div>
        <%= pm.label :name%>
        <%= pm.text_field :name %>
    </div>

    <div>
        <%= pm.label :weight%>
        <%= pm.number_field :weight %>
    </div>

    <div>
        <%= pm.label :height%>
        <%=pm.number_field :height %>
    </div>

   <div>
        <%= pm.label :width %>
        <%=pm.number_field :width %>
    </div>

   <div>
        <%= pm.label :depth%>
        <%=pm.number_field :depth %>
    </div>

    <div>
        <%= pm.label :sku%>
        <%= pm.text_field :sku %>
    </div>

    <div>
        <%= pm.label :supplier_id %>
        <%= pm.collection_select :supplier_id, @suppliers, :id, :brand_name %>
    </div>

    <div>
        <%= pm.submit 'Enviar'%>
    </div>
<%end%>

app/views/product_models/edit.html.erb
<h1> Editar Modelo de Produto </h1>

<% if(@product_model.errors.any?)%>
    <p> Verifique os erros abaixo: </p>
    <ul>
        <% @product_model.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
<%end%>

<%= render 'form' %>

app/views/product_models/index.html.erb
<h1> Modelo de Produtos </h1>

<%= link_to('Cadastrar Novo', new_product_model_path) %>

<% if @product_models.any? %>

    <%@product_models.each do | pm |%>
        <div>
        <h2><%= link_to(pm.name, pm) %></h2>
        <dl>
            <dt> SKU:</dt>
            <dd><%= pm.sku %></dd>
            <dt>Fornecedor:</dt>
            <dd><%= pm.supplier.brand_name %></dd>
        </dl>
        </div>
    <%end%>
<% else %>
    <p> Nenhum modelo de produto cadastrado. </p>
<% end %>

app/views/product_models/new.html.erb
<h1> Cadastrar Novo Modelo de Produto </h1>

<% if(@product_model.errors.any?)%>
    <p> Verifique os erros abaixo: </p>
    <ul>
        <% @product_model.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
<%end%>

<%= render 'form'%>

app/views/product_models/show.html.erb
<h1> <%= @product_model.name %></h1>
<dl>
    <dt><strong>Fornecedor: </strong></dt>
    <dd><%= @product_model.supplier.brand_name %></dd>

    <dt><strong>SKU: </strong></dt>
    <dd><%= @product_model.sku %></dd>

    <dt><strong>Dimensão: </strong></dt>
    <dd><%= @product_model.height %> cm x <%= @product_model.width %> cm x <%= @product_model.depth %> cm </dd>

    <dt><strong>Peso: </strong></dt>
    <dd><%= @product_model.weight %>g</dd>
</dl>

<div>
    <%= link_to('Editar', edit_product_model_path(@product_model))=%>
</div>
<div>
    <%= link_to('Voltar', product_models_path)%>
</div>

app/views/suppliers/_form.html.erb
<%=form_with(model: @supplier) do |s| %>
    <div>
        <%= s.label :corporate_name %>
        <%= s.text_field :corporate_name %>
    </div>

    <div>
        <%= s.label :brand_name %>
        <%= s.text_field :brand_name %>
    </div>

    <div>
        <%= s.label :registration_number %>
        <%=s.text_field :registration_number %>
    </div>

    <div>
        <%= s.label :full_address %>
        <%= s.text_field :full_address %>
    </div>

    <div>
        <%= s.label :city %>
        <%= s.text_field :city %>
    </div>

    <div>
        <%= s.label :state %>
        <%= s.text_field :state%>
    </div>

    <div>
        <%= s.label :email %>
        <%= s.text_field :email %>
    </div>

    <div>
        <%= s.label :telephone %>
        <%= s.text_field :telephone %>
    </div>

    <div>
        <%= s.submit 'Enviar'%>
    </div>
<%end%>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<% if(@supplier.errors.any?)%>
    <p> Verifique os erros abaixo: </p>
    <ul>
        <% @supplier.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
<%end%>

<%= render 'form'%>

app/views/suppliers/index.html.erb
<h1> Fornecedores </h1>

<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Localização</th>
        </tr>
    </thead>
    <tbody>
        <% @suppliers.each do |s| %>
        <tr>
            <td><%= link_to(s.brand_name, s)%></td>
            <td><%= s.city %> - <%= s.state %></td> 
        </tr>
        <%end%>
    </tbody>
</table>

<% if @suppliers.empty? %>
        <p>Não existem fornecedores cadastrados.</p>
    <% end %>

<%= link_to 'Cadastrar Fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>

<% if(@supplier.errors.any?)%>
    <p> Verifique os erros abaixo: </p>
    <ul>
        <% @supplier.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
<%end%>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1> Fornecedor <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name%></h2>

<dl>
    <dt><strong> CNPJ: </strong></dt>
    <dd><%= @supplier.registration_number%></dd>
    <dt><strong>Endereço: </strong></dt>
    <dd><%= @supplier.full_address%>, <%= @supplier.city%> - <%= @supplier.state%>
    <dt><strong> E-mail: </strong></dt>
    <dd><%= @supplier.email%></dd>
    <dt><strong> Telefone: </strong></dt>
    <dd><%= @supplier.telephone%></dd>
</dl>

<h2> Produtos deste Fornecedor</h2>
<div>
    <dl>
    <% @product_model.each do |pm| %>
        <dt><strong><%=link_to(pm.name, pm)%></strong></dt>
    <%end%>
    </dl>

<div>
    <%= link_to('Editar', edit_supplier_path(@supplier))%>
</div>
<div>
    <%= link_to('Voltar', suppliers_path)%>
</div>

app/views/warehouses/_form.html.erb
<%=form_with(model: @warehouse) do |f| %>
    <div>
        <%= f.label :name %>
        <%=f.text_field :name %>
    </div>

    <div>
        <%= f.label :description %>
        <%=f.text_area :description %>
    </div>

    <div>
        <%= f.label :code %>
        <%=f.text_field :code %>
    </div>

    <div>
        <%= f.label :address %>
        <%=f.text_field :address %>
    </div>

    <div>
        <%= f.label :city %>
        <%=f.text_field :city %>
    </div>

    <div>
        <%= f.label :cep %>
        <%=f.text_field :cep %>
    </div>

    <div>
        <%= f.label :area %>
        <%=f.number_field :area %>
    </div>

    <div>
        <%= f.submit 'Enviar'%>
    </div>
<%end%>

app/views/warehouses/edit.html.erb
<h1> Editar Galpão </h1>

<%= render 'form'%>

app/views/warehouses/new.html.erb
<h1>Novo Galpão</h1>

<% if(@warehouse.errors.any?)%>
    <p> Verifique os erros abaixo: </p>
    <ul>
        <% @warehouse.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
<%end%>

<%= render 'form' %>

app/views/warehouses/show.html.erb
<h1> Galpão <%= @warehouse.code %></h1>
<h2><%= @warehouse.description%></h2>
<div>
    <strong>Nome:</strong> <%= @warehouse.name%>
    <strong>Cidade:</strong> <%= @warehouse.city%>
    <strong>Área:</strong> <%= @warehouse.area%> m2
    <strong>Endereço:</strong> <%= @warehouse.address%> 
    <strong>CEP:</strong> <%= @warehouse.cep%>
</div>

<div>
    <%= link_to('Editar', edit_warehouse_path(@warehouse.id))%>
    <%= button_to('Remover', warehouse_path(@warehouse.id), method: :delete)%>
</div>

<div>
    <%= link_to('Voltar', root_path)%>
</div>